{
 "title": "Energy Monitoring",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Daily consumption in currency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "dataset": "iiot_gateway",
     "rawSql": "SELECT\r\n  sub.day AS \"time\",\r\n  ROUND( (SUM(sub.kwh_used) * 0.12)::numeric, 4 ) AS \"Total Cost (€)\"\r\nFROM (\r\n  SELECT\r\n    DATE_TRUNC('day', d.timestamputc) AS day,\r\n    d.sourceid,\r\n    MAX(d.value) - MIN(d.value) AS kwh_used\r\n  FROM datalog2 d\r\n  INNER JOIN sources s ON d.sourceid = s.sourceid\r\n  INNER JOIN quantities q ON d.quantityid = q.quantityid\r\n  WHERE\r\n    q.quantityname = 'Active_Energy_Delivered'\r\n    AND d.timestamputc BETWEEN $__timeFrom() AND $__timeTo()\r\n    AND s.devicename IN (\r\n      'Supply Fan',\r\n      'Exhaust Fan',\r\n      'Heat Recovery Motor',\r\n      'Pump',\r\n      'Heating Valve'\r\n    )\r\n  GROUP BY\r\n    DATE_TRUNC('day', d.timestamputc),\r\n    d.sourceid\r\n) AS sub\r\nGROUP BY sub.day\r\nORDER BY \"time\" ASC;\r\n"
    }
   ]
  },
  {
   "title": "Total Daily Energy",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "iiot_gateway",
     "rawSql": "WITH daily_last AS (\r\n    SELECT DISTINCT ON (s.devicename, q.quantityname, DATE(d.timestamputc))\r\n        DATE(d.timestamputc) AS day,\r\n        s.devicename,\r\n        q.quantityname,\r\n        d.value\r\n    FROM datalog2 d\r\n    JOIN sources s ON d.sourceid = s.sourceid\r\n    JOIN quantities q ON d.quantityid = q.quantityid\r\n    WHERE\r\n        q.quantityname IN (\r\n            'Active_Energy_Delivered',\r\n            'Active_Energy_Received'\r\n        )\r\n        AND s.devicename IN (\r\n            'Supply Fan',\r\n            'Exhaust Fan',\r\n            'Heat Recovery Motor',\r\n            'Pump'\r\n        )\r\n        AND $__timeFilter(d.timestamputc)\r\n    ORDER BY\r\n        s.devicename,\r\n        q.quantityname,\r\n        DATE(d.timestamputc),\r\n        d.timestamputc DESC\r\n),\r\ndaily_diff AS (\r\n    SELECT\r\n        day,\r\n        devicename,\r\n        quantityname,\r\n        value - LAG(value) OVER (\r\n            PARTITION BY devicename, quantityname\r\n            ORDER BY day\r\n        ) AS daily_energy\r\n    FROM daily_last\r\n),\r\naggregated AS (\r\n    SELECT\r\n        day,\r\n        quantityname,\r\n        SUM(daily_energy) AS energy\r\n    FROM daily_diff\r\n    WHERE daily_energy IS NOT NULL\r\n    GROUP BY day, quantityname\r\n)\r\nSELECT\r\n    day AS time,\r\n    quantityname AS metric,\r\n    energy\r\nFROM aggregated\r\n\r\nUNION ALL\r\n\r\nSELECT\r\n    day AS time,\r\n    'Net_Energy' AS metric,\r\n    SUM(\r\n        CASE\r\n            WHEN quantityname = 'Active_Energy_Delivered' THEN energy\r\n            WHEN quantityname = 'Active_Energy_Received'  THEN -energy\r\n        END\r\n    ) AS energy\r\nFROM aggregated\r\nGROUP BY day\r\n\r\nORDER BY time, metric;\r\n\r\n"
    }
   ]
  },
  {
   "title": "Total Active Energy Delivered",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iiot_gateway",
     "rawSql": "SELECT\r\n    SUM(latest.value) AS total_active_energy,\r\n    MAX(latest.unit) AS unit\r\nFROM (\r\n    SELECT DISTINCT ON (s.devicename)\r\n        s.devicename,\r\n        d.value,\r\n        q.unit\r\n    FROM datalog2 d\r\n    JOIN sources s ON d.sourceid = s.sourceid\r\n    JOIN quantities q ON d.quantityid = q.quantityid\r\n    WHERE q.quantityname = 'Active_Energy_Delivered'\r\n      AND s.devicename IN (\r\n         'Supply Fan',\r\n         'Exhaust Fan',\r\n         'Heat Recovery Motor',\r\n         'Pump'\r\n      )\r\n    ORDER BY s.devicename, d.timestamputc DESC\r\n) latest;"
    }
   ]
  },
  {
   "title": "Total Active Power",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iiot_gateway",
     "rawSql": "SELECT\r\n    SUM(latest.value) AS total_active_power,\r\n    MAX(latest.unit) AS unit\r\nFROM (\r\n    SELECT DISTINCT ON (s.devicename)\r\n        s.devicename,\r\n        d.value,\r\n        q.unit\r\n    FROM datalog2 d\r\n    JOIN sources s ON d.sourceid = s.sourceid\r\n    JOIN quantities q ON d.quantityid = q.quantityid\r\n    WHERE q.quantityname = 'Active_Power_Total'\r\n      AND s.devicename IN (\r\n          'Supply Fan',\r\n          'Exhaust Fan',\r\n          'Heat Recovery Motor',\r\n          'Pump'\r\n      )\r\n    ORDER BY s.devicename, d.timestamputc DESC\r\n) latest;"
    }
   ]
  },
  {
   "title": "Energy consumption per hour",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 14 },
   "targets": [
    {
     "dataset": "iiot_gateway",
     "rawSql": "SELECT\r\n    date_trunc('hour', d.timestamputc) AS hour,\r\n    s.devicename,\r\n    MAX(d.value) - MIN(d.value) AS energy_consumed,\r\n    q.unit\r\nFROM datalog2 d\r\nJOIN sources s ON d.sourceid = s.sourceid\r\nJOIN quantities q ON d.quantityid = q.quantityid\r\nWHERE q.quantityname = 'Active_Energy_Delivered'\r\n  AND s.devicename IN (\r\n      'Supply Fan',\r\n      'Exhaust Fan',\r\n      'Heat Reovery Pump',\r\n      'Pump'\r\n  )\r\nGROUP BY\r\n    hour,\r\n    s.devicename,\r\n    q.unit\r\nORDER BY\r\n    hour DESC,\r\n    s.devicename;"
    }
   ]
  },
  {
   "title": "Device Power",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "iiot_gateway",
     "rawSql": "SELECT DISTINCT ON (s.devicename, q.quantityname)\r\n    s.devicename,\r\n    q.quantityname,\r\n    d.timestamputc,\r\n    d.value,\r\n    q.unit\r\nFROM datalog2 d\r\nJOIN sources s ON d.sourceid = s.sourceid\r\nJOIN quantities q ON d.quantityid = q.quantityid\r\nWHERE q.quantityname IN (\r\n\t'Active_Power_Total', \r\n\t'Reactive_Power_Total', \r\n\t'Apparent_Power_Total'\r\n\t\t\t\t\t\t)\r\n  AND s.devicename IN (\r\n      'Supply Fan',\r\n      'Exhaust Fan',\r\n      'Heat Recovery Motor',\r\n      'Pump'\r\n  )\r\nORDER BY s.devicename, q.quantityname, d.timestamputc DESC;"
    }
   ]
  },
  {
   "title": "Latest active energy by device",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iiot_gateway",
     "rawSql": "SELECT DISTINCT ON (s.devicename)\r\n    s.devicename,\r\n    d.timestamputc,\r\n    d.value,\r\n    q.unit\r\nFROM datalog2 d\r\nJOIN sources s ON d.sourceid = s.sourceid\r\nJOIN quantities q ON d.quantityid = q.quantityid\r\nWHERE q.quantityname = 'Active_Energy_Delivered'\r\n  AND s.devicename IN (\r\n      'Supply Fan',\r\n      'Exhaust Fan',\r\n      'Heat Recovery Motor',\r\n      'Pump'\r\n  )\r\nORDER BY s.devicename, d.timestamputc DESC;"
    }
   ]
  }
 ]
}