{
 "title": "HVAC System",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Outdor Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "iiot_gateway",
     "rawSql": "SELECT\r\n    sd.timestamp,\r\n    sd.field_value as value,\r\n    mv.browse_name\r\nFROM sensor_data sd\r\nJOIN opcua_monitored_variables mv\r\n    ON sd.measurement = mv.measurement_name\r\nWHERE mv.browse_name = 'OutdoorTemp_GT10_01'\r\nORDER BY sd.timestamp DESC\r\nLIMIT 100;"
    }
   ]
  },
  {
   "title": "Outdoor Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iiot_gateway",
     "rawSql": "SELECT\r\n    sd.timestamp,\r\n    sd.field_value as value,\r\n    mv.browse_name\r\nFROM sensor_data sd\r\nJOIN opcua_monitored_variables mv\r\n    ON sd.measurement = mv.measurement_name\r\nWHERE mv.browse_name = 'OutdoorTemp_GT10_01'\r\nORDER BY sd.timestamp DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "NightCooling IndoorG",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "iiot_gateway",
     "rawSql": "SELECT * FROM public.sensor_data\r\nWHERE field_name = 'NightCooling_IndoorG'"
    }
   ]
  }
 ]
}