{
 "title": "HVAC System",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Expose simulated sensors on outputs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "iiot_gateway",
     "rawSql": "SELECT\r\n  timestamp AS \"time\",\r\n  MAX(CASE WHEN field_name = 'Sim_SupplyTemp_GT71_01' THEN field_value END) AS \"Supply Temp GT71_01\",\r\n  MAX(CASE WHEN field_name = 'Sim_ExhaustTemp_GT72_01' THEN field_value END) AS \"Exhaust Temp GT72_01\",\r\n  MAX(CASE WHEN field_name = 'Sim_ReturnTemp_GT81_01' THEN field_value END) AS \"Return Temp GT81_01\"\r\nFROM sensor_data\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND field_name IN (\r\n    'Sim_SupplyTemp_GT71_01',\r\n    'Sim_ExhaustTemp_GT72_01',\r\n    'Sim_ReturnTemp_GT81_01'\r\n  )\r\nGROUP BY timestamp\r\nORDER BY timestamp ASC\r\n\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Heating Energy Valve SV71_01",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "iiot_gateway",
     "rawSql": "SELECT\r\n    sd.timestamp,\r\n    sd.field_value as value,\r\n    mv.browse_name\r\nFROM sensor_data sd\r\nJOIN opcua_monitored_variables mv\r\n    ON sd.measurement = mv.measurement_name\r\nWHERE mv.browse_name = 'SV71_01_Pct'\r\nORDER BY sd.timestamp DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "VVX - Heat Regenerator",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iiot_gateway",
     "rawSql": "SELECT\r\n    sd.timestamp,\r\n    sd.field_value as value,\r\n    mv.browse_name\r\nFROM sensor_data sd\r\nJOIN opcua_monitored_variables mv\r\n    ON sd.measurement = mv.measurement_name\r\nWHERE mv.browse_name = 'VVX_ControlPct'\r\nORDER BY sd.timestamp DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Outdor Temperature GT10_01",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "dataset": "iiot_gateway",
     "rawSql": "SELECT\r\n    sd.timestamp,\r\n    sd.field_value as value,\r\n    mv.browse_name\r\nFROM sensor_data sd\r\nJOIN opcua_monitored_variables mv\r\n    ON sd.measurement = mv.measurement_name\r\nWHERE mv.browse_name = 'OutdoorTemp_GT10_01'\r\nORDER BY sd.timestamp DESC\r\nLIMIT 100;"
    }
   ]
  },
  {
   "title": "Outdoor Humidity GT10_01",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "dataset": "iiot_gateway",
     "rawSql": "SELECT\r\n    sd.timestamp,\r\n    sd.field_value as value,\r\n    mv.browse_name\r\nFROM sensor_data sd\r\nJOIN opcua_monitored_variables mv\r\n    ON sd.measurement = mv.measurement_name\r\nWHERE mv.browse_name = 'OutdoorHumidity_GT10_01'\r\nORDER BY sd.timestamp DESC\r\nLIMIT 100;\r\n"
    }
   ]
  },
  {
   "title": "Heating Pump P701_01",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "dataset": "iiot_gateway",
     "rawSql": "SELECT\r\n    sd.timestamp AS \"time\",\r\n    sd.field_value::int AS \"value\"\r\nFROM sensor_data sd\r\nJOIN opcua_monitored_variables mv\r\n    ON sd.measurement = mv.measurement_name\r\nWHERE\r\n    mv.browse_name = 'P701_01_CMD'\r\n    AND $__timeFilter(sd.timestamp)\r\nORDER BY sd.timestamp ASC;\r\n"
    }
   ]
  },
  {
   "title": "Valves",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "dataset": "iiot_gateway",
     "rawSql": "SELECT\r\n  timestamp AS \"time\",\r\n  MAX(CASE WHEN field_name = 'ST72_01_Close' THEN field_value END) AS \"ST72_01\",\r\n  MAX(CASE WHEN field_name = 'ST73_01_Close' THEN field_value END) AS \"ST73_01\"\r\nFROM sensor_data\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND field_name IN (\r\n    'ST72_01_Close',\r\n    'ST73_01_Close'\r\n  )\r\nGROUP BY timestamp\r\nORDER BY timestamp ASC\r\n"
    }
   ]
  }
 ]
}